services:
  - type: web
    name: isi-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: GOOGLE_MAPS_MAP_ID
        sync: false

  - type: static
    name: isi2
    buildCommand: ""
    staticPublishPath: frontend
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
